; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = waveshareEpaper
; custom common options

[env]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    SPI
    Wire
    ArduinoJson@7.0
    Adafruit GFX Library@1.11
    WiFiClientSecure@2.0.0

monitor_speed = 115200
upload_speed = 2000000

;build_flags =
;    -D VERSION=1.2.3
;    -D DEBUG=1

[env:waveshareEpaper]
board = esp32dev
build_flags =
    -D WAVESHARE_EPAPER


[env:lilygoT5]
;https://github.com/Xinyuan-LilyGO/LilyGo-T5-Epaper-Series
; and https://github.com/Xinyuan-LilyGO/LilyGo-T5-Grayscale
board = esp32dev
build_flags =
    -D LILYGO_T5_V213